( 'rDur': 0.16, 'ampMod': 0.0, 'rPitch': 0.0, 'toggle': 0, 
  'rFill': 0.0, 'pitch': 0.0, 'qHi': 1.0, 'rAmp': 0.05, 'rPitchMod': 0.0, 
  'pitchMod': 0.0, 'timeArr': [ 0.3, 0.3, 0.3 ], 'send': 0.0, 'posMod': 1.0, 'dur': 0.10212147927628, 
  'rAmpMod': 0.0, 'pan': 0.0, 'dir': 0.0, 'delay': 0.0, 'rDurMod': 0.0, 
  'rFillMod': 0.0, 'qLo': 1.0, 'pos': 0.0, 'waveform': SoundFileView.new, 'rPos': 0.07, 
  'envCurve': -5.0, 'filtFreqLo': 20000.0, 'rPosMod': 0.0, 'vol': 1.0, 'ampArr': [ 0, 1, 1, 0 ], 
  'fillFactor': 2.0, 'filtFreqHi': 50.0, 'durMod': 0.0, 'fillMod': 0.0 )