( 'rDur': 0.09, 'ampMod': 0.0, 'rPitch': 0.0, 'toggle': 1, 
  'rFill': 0.38, 'pitch': 0.0, 'qHi': 1.0, 'rAmp': 0.0, 'rPitchMod': 0.0, 
  'pitchMod': 0.0, 'timeArr': [ 0.3, 0.3, 0.3 ], 'send': 0.0, 'posMod': 0.86, 'dur': 0.020434212357865, 
  'rAmpMod': 0.0, 'pan': 0.0, 'dir': 0.44380871460836, 'delay': 0.40085039567686, 'rDurMod': 0.0, 
  'rFillMod': 0.0, 'qLo': 1.0, 'pos': 0.10501193317422, 'waveform': SoundFileView.new, 'rPos': 0.3, 
  'envCurve': -2.0, 'filtFreqLo': 1844.0, 'rPosMod': 0.0, 'vol': 1.0, 'path': "/media/Data/Dropbox/Weltherrschaft3500/LIVE/2016/Surge/SAMPLES/Surge_Perc_A.wav", 
  'ampArr': [ 0, 1, 1, 0 ], 'fillFactor': 3.9707051869093, 'filtFreqHi': 588.0, 'durMod': 0.23, 'fillMod': 0.2 )