{
	// joy funcs:
	// Buttons:
	~joy.slot(1, 288).action_{|slot|

	};

	~joy.slot(1, 290).action_{|slot|

	};

	~joy.slot(1, 291).action_{|slot|

	};

	~joy.slot(1, 292).action_{|slot|

	};

	~joy.slot(1, 293).action_{|slot|

	};

	// Axis:
	~joy.slot(3, 0).action_{|slot|

	};

	~joy.slot(3, 1).action_{|slot|

	};

	~joy.slot(3, 5).action_{ |slot|

	};

	~joy.slot(3, 6).action_{|slot|

	};

	~joy.slot(3, 16).action_{|slot|

	};

	~joy.slot(3, 17).action_{|slot|

	};
}.defer;